# -*- coding: utf-8 -*-
"""Python_RPS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19mKx1tBmRcu2JYdL6lC8xjhsHAwHAHE9
"""



import random

wins = 0
losses = 0
ties = 0

def play(player):
    global wins, losses, ties

    m = ("rock", "paper", "scissors")
    computer = m[random.randrange(len(m))]
    if player == computer:
        result = "it's a tie"
        ties += 1
    elif player == "rock" and computer == "scissors":
        result = "you win"
        wins += 1
    elif player == "paper" and computer == "rock":
        result = "you win"
        wins += 1
    elif player == "scissors" and computer == "paper":
        result = "you win"
        wins += 1
    else:
        result = "you lose"
        losses += 1

    print(
        "you: {}\n"
        "computer: {}\n"
        "--> {}".format(player, computer, result)
    )

def start():
    global wins, losses, ties
    print("rock\npaper\nscissors")
    while True:
        player = input("rock, paper, scissors or exit: ").strip().lower()
        if player == "exit":
            break
        elif player in ("rock", "paper", "scissors"):
            play(player)
        else:
            print("Please choose rock, paper, scissors or exit.")

    if wins > losses:
        print("\nCongratulations! You won the game!")
    elif losses > wins:
        print("\nSorry, you lost the game :(")
    else:
        print("\nThe game ended in a tie.")



def greet():
    print('Welcome To The Rock, Paper, Scissors Game.')
    name = input('What is your name? ')
    print('Hello', name)

    while True:
        print('Do you want to play the game [yes or no]?')
        ans = input().strip().lower()
        if ans == 'yes':
            print('There are 3 options, please choose 1')
            start()
            break
        elif ans == 'no':
            print("OK. Have a good day!")
            break
        else:
            print("Please type 'yes' or 'no'.")

if __name__ == "__main__":
    greet()